---
title: Lexical Richness Over The 17-20th Centuries
author: by Sarah Winne
output: github_document
---

## Summary

A point to be highlighted before beginning, is that lexical richness, or variety of vocabulary, does not directly correlate to a good quality book. There are many well written books with a simple vocabulary, as well as ones with large vocabularies. 

Basically, the form of literature, whether the author was a parent, and what decade or century they published in were the most helpful for predicting lexical richness. Depending on the forms, lexical richness went up a few hundread of varying amounts. If they had no children, it was estimated to go down about 17.39, and for every increase in decade, it went down by about 1.26. So while there aren't incredibly significant negative changes, over time lexical richness did go down. The decrease is more apparent if you focus on the 19th-20th centuries, as during the 17th-18th lexical richness stays pretty constant. There is the fact that the dataset from Project Gutenberg has fewer books from that time period, as compared to the 19th-20th centuries. 

While the average and median lexical richness do decrease more over the 19th-20th centuries, there is also a wider range of lexical richnesses in both the positive and negative directions. 



Write-up of your project and findings go here. 
Think of this as the text of your presentation. 
Roughly 750 words. As long as you're in the ballpark of 750 words, you're good! Ignore code chunks and only count the words in prose. If using code, only one most important. 

```{r load-data, echo = FALSE}
#gutenberg <- read_csv("/cloud/project/data/ProjectGutenbergMetadata.csv")
```

## Presentation

My presentation can be found [here](presentation/presentation.html).

## Data 

Langer, Lars, 2023, "Project Gutenberg creative literature life circumstance & work metadata collection", https://doi.org/10.7910/DVN/7POSNW, Harvard Dataverse, V2, UNF:6:WFz+c8P5K2WApDFQRc+RNw== [fileUNF], Accessed March 9, 2024

## References

Langer, Lars, 2023, "Project Gutenberg creative literature life circumstance & work metadata collection", https://doi.org/10.7910/DVN/7POSNW, Harvard Dataverse, V2, UNF:6:WFz+c8P5K2WApDFQRc+RNw== [fileUNF], Accessed March 9, 2024

