---
title: Lexical Richness Over The 17th-20th Centuries - Plots
author: by Sarah Winne
output: github_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(tidymodels)
library(broom)
```

## Scratch Work

```{r load-data, echo = FALSE}
gutenberg <- read_csv("/cloud/project/data/ProjectGutenbergMetadata.csv")
```

```{r}
gutenberg <- gutenberg %>%
  mutate("century" = (floor(Year_Publication/100)*100)) %>%
  mutate("decade" = (floor(Year_Publication/10)*10)) %>%
  mutate("age_by10" = (floor(Age_Publication/10)*10))
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(x = Lexical_Richness, y = decade, color = century, alpha = .1)) +
  geom_point()
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(y = Lexical_Richness, x = decade, color = century, alpha = .1)) +
  geom_point() +
  geom_smooth(color = "black", method = "lm", se = FALSE) 
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(y = Lexical_Richness, x = decade, color = century, alpha = .1)) +
  geom_point() +
  geom_smooth(color = "black", method = "lm", se = FALSE) +
  facet_wrap(~ age_by10)
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(y = Lexical_Richness, x = Year_Publication, color = century, alpha = .1)) +
  geom_point() +
  geom_smooth(color = "black", method = "lm", se = FALSE)
```

```{r}
gutenberg %>%
  mutate(Year_Publication = if_else(Year_Publication>=1800, Year_Publication, NA)) %>%
  ggplot(mapping = aes(y = Lexical_Richness, x = Year_Publication, color = century, alpha = .1)) +
  geom_point() +
  geom_smooth(color = "black", method = "lm", se = FALSE)
```

```{r}
gutenberg %>%
  mutate(Year_Publication = if_else(Year_Publication<=1800, Year_Publication, NA)) %>%
  ggplot(mapping = aes(y = Lexical_Richness, x = Year_Publication, color = century, alpha = .1)) +
  geom_point() +
  geom_smooth(color = "black", method = "lm", se = FALSE)
```

```{r}
gutenberg %>%
  mutate(Year_Publication = if_else(Year_Publication<=1800, Year_Publication, NA)) %>%
  ggplot(mapping = aes(x = as_factor(century))) +
  geom_bar()
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(y = Lexical_Richness, x = Year_Publication, color = century, alpha = .1)) +
  geom_point() +
  geom_smooth(color = "black", se = FALSE)
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(x = Lexical_Richness, y = Literature_Form, color = century, alpha = .1)) +
  geom_jitter()
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(y = century, fill = Literature_Form, color = Literature_Form)) +
  geom_bar(position = "fill") 
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(x = Lexical_Richness, y = Literature_Form, fill = century)) +
  geom_bar(stat = "identity")
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(y = Lexical_Richness, x = Year_Publication, color = century, alpha = .1)) +
  geom_point() +
  geom_smooth(color = "black", se = FALSE) +
  facet_wrap(~Highest_Education)
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(y = Lexical_Richness, x = decade, color = century, alpha = .1)) +
  geom_point() +
  geom_smooth(color = "black", se = FALSE) +
  facet_wrap( ~ Parenthood)
```

```{r}
gutenberg %>%
  ggplot(mapping = aes(y = Lexical_Richness, x = decade, group = century, alpha = 0.1)) +
  geom_boxplot()
```

